version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: ./app
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings
    command: 
      - /bin/bash
      - -c
      - |
        python manage.py migrate
        python -m django_createsuperuser "admin" "admin" admin@example.com
        python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/code
    ports:
      - "8000:8000"
    depends_on:
      - db